### PR TITLE
update installation doc

### PR DESCRIPTION
**Pull request by mesaglio**
#40

### CODE REVIEW

**Review by imthaghost — APPROVED** [review]
LGTM

**Review by imthaghost — APPROVED** [review]

**Comment by tmcolby** [comment]
this does not work for me.  

```
go install github.com/imthaghost/goclone@latest
go: github.com/imthaghost/goclone@latest: module github.com/imthaghost/goclone@latest found (v1.2.0), but does not contain package github.com/imthaghost/goclone
```

**Comment by mesaglio** [comment]
@tmcolby thanks for your feedback, can you please check the following installation command
```bash
go install github.com/imthaghost/goclone/cmd/goclone@latest
```

**Comment by Dodain** [comment]
@mesaglio 
go version  1.18.1

after running "go install github.com/imthaghost/goclone/cmd/goclone@latest"

getting "goclone: command not found"

**Comment by mesaglio** [comment]
@Dodain do you have the golang binary path in your PATH env var?

I tested on docker with you go version and it works.
```bash
> docker run -it golang:1.18.1-alpine sh
> /go: go install github.com/imthaghost/goclone/cmd/goclone@latest
. . .
> /go:  goclone
Usage:
  goclone <url> [flags]

Flags:
  -C, --cookie strings        Pre-set these cookies
  -h, --help                  help for goclone
  -o, --open                  Automatically open project in deafult browser
  -p, --proxy_string string   Proxy connection string. Support http and socks5 https://pkg.go.dev/github.com/gocolly/colly#Collector.SetProxy
  -s, --serve                 Serve the generated files using Echo.
  -u, --user_agent string     Custom User Agent
```

What is your PATH env value?

**Pull request merged**
